const BYTES_PER_SECTOR = 256;
const BYTES_PER_SEAL = 4 * 1024; // 4 KB
const BYTES_PER_PAD = 16 * 1024; // 16 KB
const BYTES_PER_LOAD = 256 * 1024; // 256 KB
const BYTES_PER_PRICE = 8 * 1024 * 1024 * 1024; // 8 GB
const BYTES_PER_SEGMENT = 256 * 1024; // 256 KB

const BYTES_PER_UNIT = 32;
const BYTES_PER_BHASH = 64;

const UNITS_PER_SECTOR = BYTES_PER_SECTOR / BYTES_PER_UNIT;
const UNITS_PER_SEAL = BYTES_PER_SEAL / BYTES_PER_UNIT;

const SECTORS_PER_SEAL = BYTES_PER_SEAL / BYTES_PER_SECTOR;
const SECTORS_PER_PRICE = BYTES_PER_PRICE / BYTES_PER_SECTOR;
const SECTORS_PER_LOAD = BYTES_PER_LOAD / BYTES_PER_SECTOR;
const SECTORS_PER_SEGMENT = BYTES_PER_SEGMENT / BYTES_PER_SECTOR;

const SEALS_PER_LOAD = BYTES_PER_LOAD / BYTES_PER_SEAL;
const PADS_PER_LOAD = BYTES_PER_LOAD / BYTES_PER_PAD;

const SEALS_PER_PAD = SEALS_PER_LOAD / PADS_PER_LOAD;
const BHASHES_PER_SEAL = BYTES_PER_SEAL / BYTES_PER_BHASH;
const BHASHES_PER_PAD = BYTES_PER_PAD / BYTES_PER_BHASH;

export {
    BYTES_PER_SECTOR,
    BYTES_PER_SEAL,
    BYTES_PER_PAD,
    BYTES_PER_LOAD,
    BYTES_PER_PRICE,
    BYTES_PER_SEGMENT,
    BYTES_PER_UNIT,
    BYTES_PER_BHASH,
    UNITS_PER_SECTOR,
    UNITS_PER_SEAL,
    SECTORS_PER_SEAL,
    SECTORS_PER_PRICE,
    SECTORS_PER_LOAD,
    SECTORS_PER_SEGMENT,
    SEALS_PER_LOAD,
    PADS_PER_LOAD,
    SEALS_PER_PAD,
    BHASHES_PER_SEAL,
    BHASHES_PER_PAD,
};
